name: Build Linux

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
        architecture: [x86_64, arm64]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace swift:6.0.3-focal swift build -c release -Xswiftc -static-stdlib
        ls -la .build
        zip_file="adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip"
        cp -r .build/x86_64-unknown-linux-gnu/release/adventure .
        cp -r .build/x86_64-unknown-linux-gnu/release/adventure_adventure.bundle .
        zip -r $zip_file adventure adventure_adventure.resources

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: 'Testing Release'
        prerelease: true
        tag_name: testing_release
        target_commitish: ${{ github.sha }}
        files: |
          adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip
