name: Build Windows

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
defaults:
  run:
    shell: pwsh

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest]
        architecture: [x86_64]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0.3"

    - name: Build
      run: |
        swift build -c release
        ls .build
        zip_file="adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip"
        cp -r .build/x86_64-pc-windows-msvc/release/adventure.exe .
        cp -r .build/x86_64-pc-windows-msvc/release/adventure_adventure.resources .
        zip -r $zip_file adventure.exe adventure_adventure.resources

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: 'Testing Release'
        prerelease: true
        tag_name: testing_release
        target_commitish: ${{ github.sha }}
        files: |
          adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip
