name: Build Macos

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest]
        architecture: [x86_64, arm64]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0.3"

    - name: Build
      run: |
        swift build -c release
        ls -la .build
        zip_file="adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip"
        zip -r $zip_file .build/arm64-apple-macosx/release/adventure .build/arm64-apple-macosx/release/adventure_adventure.bundle

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: 'Testing Release'
        prerelease: true
        tag_name: testing_release
        target_commitish: ${{ github.sha }}
        files: |
          adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip
