name: Build Macos

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest]
        architecture: [x86_64, arm64]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0.3"
    - name: Build
      run: |
        swift build -c release
        zip_file="adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip"
        zip -r $zip_file .build/release/adventure .build/release/adventure_adventure.resources
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: true
        files: |
          adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip
