name: Build Windows

on:
  workflow_dispatch:
  push:
    branches:
      - master
defaults:
  run:
    shell: pwsh

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest]
        architecture: [x86_64]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v4

    - uses: SwiftyLab/setup-swift@latest
      with:
        swift-version: "6.0.3"
    # TODO: make the user not need to install swift for this to work
    - name: Build
      run: |
        swift build -c release
        ls .build
        ls .build/x86_64-unknown-windows-msvc/release
        cp -r .build/x86_64-unknown-windows-msvc/release/adventure.exe .
        cp -r .build/x86_64-unknown-windows-msvc/release/adventure_adventure.resources .
        $zipFile = "adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip"
        Compress-Archive -Path "adventure.exe", "adventure_adventure.resources" -DestinationPath $zipFile
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: 'Testing Release'
        prerelease: true
        tag_name: testing_release
        target_commitish: ${{ github.sha }}
        files: |
          adventure_${{ matrix.platform }}_${{ matrix.architecture }}.zip
