name: Test
on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - '.github/ISSUE_TEMPLATE/**'
  workflow_dispatch:
jobs:
  build_linux:
    strategy:
      fail-fast: true
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace swift:6.1-focal swift build -c release -Xswiftc -static-stdlib
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            .build/x86_64-unknown-linux-gnu/release/TerminalKingdom_TerminalKingdom
            .build/x86_64-unknown-linux-gnu/release/TerminalKingdom_TerminalKingdom.resources
          if-no-files-found: error
          retention-days: 2
  build_macos:
    strategy:
      fail-fast: true
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.1"
      - name: Build
        run: |
          swift build -c release
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: |
            .build/arm64-apple-macosx/release/TerminalKingdom
            .build/arm64-apple-macosx/release/TerminalKingdom_TerminalKingdom.bundle
          retention-days: 2
  build_windows:
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest]
        architecture: [x86_64]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.1"
      - name: Build
        shell: pwsh
        run: |
          swift build -c release
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: .build/release/
          retention-days: 2
