name: Update Release

on:
  workflow_run:
    workflows: ["Build Linux", "Build Macos"]
    types:
      - completed

jobs:
  update_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Release ID by Name
        id: get_release
        run: |
          release_name="testing release"
          release_id=$(gh release list --json id,tagName,name -q ".[] | select(.name == \"${release_name}\") | .id")
          if [ -z "$release_id" ]; then
            echo "Release '${release_name}' not found."
            exit 1
          fi
          echo "release_id=${release_id}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List existing release assets
        id: list_assets
        run: |
          release_assets=$(gh release view "${{ env.release_id }}" --json assets -q ".assets[].id")
          echo "release_assets=${release_assets}" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete old release assets
        run: |
          for asset_id in ${{ env.release_assets }}; do
            gh release delete "${asset_id}" --yes
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          path: ./macos-artifacts

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          path: ./linux-artifacts

      - name: Update existing release with new artifacts
        run: |
          for artifact in ./macos-artifacts/*.zip; do
            gh release upload ${{ env.release_id }} $artifact --clobber
          done
          for artifact in ./linux-artifacts/*.zip; do
            gh release upload ${{ env.release_id }} $artifact --clobber
          done

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
